### ISSUE TITLE
不停爬到同意协议页面

### ISSUE THREAD

**Issue by Orwlit** [A-BigTree/hotel_Crawling#1]
我已经按照README中内容配置好了cookie和user-agent，第一次运行程序时看到终端里确实在爬酒店信息，然后取消了想等下继续弄。
结果第二次运行后终端里循环打印如下信息：
```
city: 北京地区, offset: 0
Page hotel num: 0
```
经过debug之后，我确定了问题出在`get_response()`函数，因为爬到了同意协议页面，所以解析不出来任何酒店信息。
我把cookie清除后在Chrome里手动同意了协议，并使用新cookie尝试爬取页面，但还是相同结果。

为什么会第一次能运行成功，但之后再也没成功过？有什么跳过用户同意协议页面的方法吗？谢谢！

**Comment by A-BigTree** [comment]
booking的反爬机制比较厉害，想要跳过那个页面可能需要代理池或者更高级的防反爬的方法，这里没有使用这种方法，所以可以<u>清一下浏览器的cookie缓存，重新更新一下cookie设置</u>，或者 **架梯子** 👍

**Comment by Orwlit** [comment]
清cookie并不管用，架梯子的话不知道为什么我本地https的ssl配置可能有点问题，暂时没有尝试成功。

你那边有通过架梯子成功破除过协议页面吗？我看你代码中的`requests.get`中并没有包含`proxies`
如果方便的话你可以在你本地测试一下吗，有没有除了第一次成功运行外一直爬到协议页面的现象

除此之外我还在云服务器上测试了一下（Vultr服务器，ip在美国）。就很奇怪，一样的配置文件，得到的结果也一样：第一次能运行，第二次开始爬到协议页面，不知道是哪里出了问题。

**Comment by A-BigTree** [comment]
我知道可能是什么问题了，请求参数里面有`aid`访问者ID需要更新[说明在这里](https://github.com/A-BigTree/hotel_Crawling#%E5%9F%BA%E4%BA%8E%E5%9F%8E%E5%B8%82id%E7%9A%84%E5%8F%82%E6%95%B0%E8%AE%BE%E7%BD%AE%E6%8E%A8%E8%8D%90)，在打开Booking网站时，链接上可以拿到，可以更新试一试

**Comment by yeuei** [comment]
不知道是实效过了还是怎么的，这个XPATH路径似乎都失效了
